# Generated by Django 6.0.5 on 2026-05-28 09:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('PUSH', 'Push Notification (FCM)'), ('SMS', 'SMS'), ('EMAIL', 'Email'), ('IN_APP', 'In-App Notification'), ('WHATSAPP', 'WhatsApp (future)')], max_length=10)),
                ('notification_type', models.CharField(max_length=50)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField()),
                ('data', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued in Celery'), ('SENT', 'Sent to Provider'), ('DELIVERED', 'Delivered to Device'), ('FAILED', 'Failed to Send'), ('BOUNCED', 'Bounced / Invalid')], default='QUEUED', max_length=10)),
                ('provider_message_id', models.CharField(blank=True, max_length=255)),
                ('failure_reason', models.TextField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notifications_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('push_enabled', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=True)),
                ('email_enabled', models.BooleanField(default=True)),
                ('marketing_push', models.BooleanField(default=False)),
                ('marketing_email', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'notifications_preference',
            },
        ),
    ]
