# Generated by Django 6.0.5 on 2026-05-28 09:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyContactAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact_name', models.CharField(max_length=150)),
                ('contact_phone', models.CharField(max_length=20)),
                ('sms_sent', models.BooleanField(default=False)),
                ('sms_delivered', models.BooleanField(default=False)),
                ('call_attempted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'sos_emergency_contact_alert',
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incident_type', models.CharField(choices=[('GUARD_MISCONDUCT', 'Guard Misconduct'), ('GUARD_NO_SHOW', 'Guard Did Not Arrive'), ('GUARD_EARLY_DEPARTURE', 'Guard Left Early'), ('THREATENING_BEHAVIOUR', 'Threatening Behaviour'), ('THEFT', 'Theft'), ('PROPERTY_DAMAGE', 'Property Damage'), ('DANGEROUS_CLIENT', 'Dangerous Client (Guard Report)'), ('SAFETY_CONCERN', 'General Safety Concern'), ('OTHER', 'Other')], max_length=30)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', 'Open — Under Investigation'), ('IN_REVIEW', 'In Review'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed — No Action')], db_index=True, default='OPEN', max_length=15)),
                ('resolution_notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sos_incident',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='incidents/evidence/')),
                ('file_type', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video')], max_length=10)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'sos_incident_evidence',
            },
        ),
        migrations.CreateModel(
            name='SOSAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trigger_method', models.CharField(choices=[('BUTTON', 'Manual Button Press'), ('SHAKE', 'Shake Gesture'), ('AUTO_CHECKIN', 'Auto — Missed Check-in Escalation'), ('GUARD_OFFLINE', 'Auto — Guard Went Offline During Session'), ('GUARD_DISTRESS', 'Guard Distress Button')], max_length=20)),
                ('status', models.CharField(choices=[('TRIGGERED', 'Triggered — Awaiting Acknowledgement'), ('ACKNOWLEDGED', 'Acknowledged by Control Room'), ('RESPONDING', 'Response Team Dispatched'), ('RESOLVED', 'Resolved'), ('FALSE_ALARM', 'Resolved — False Alarm')], db_index=True, default='TRIGGERED', max_length=15)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('location_accuracy_meters', models.FloatField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('recording_file', models.FileField(blank=True, null=True, upload_to='sos/recordings/')),
            ],
            options={
                'db_table': 'sos_alert',
                'ordering': ['-created_at'],
            },
        ),
    ]
