# Generated by Django 6.0.5 on 2026-05-28 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_initial'),
        ('sos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='assigned_to',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incident',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='incident',
            name='filed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='filed_incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incidentevidence',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='sos.incident'),
        ),
        migrations.AddField(
            model_name='sosalert',
            name='assigned_to',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_sos_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sosalert',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sos_alerts', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='sosalert',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sos_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emergencycontactalert',
            name='sos_alert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_alerts', to='sos.sosalert'),
        ),
        migrations.AddIndex(
            model_name='sosalert',
            index=models.Index(fields=['status', 'created_at'], name='sos_alert_status_8eeaa4_idx'),
        ),
        migrations.AddIndex(
            model_name='sosalert',
            index=models.Index(fields=['user', 'created_at'], name='sos_alert_user_id_fa146e_idx'),
        ),
    ]
