# Generated by Django 6.0.5 on 2026-05-28 09:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTPToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('otp_hash', models.CharField(max_length=64)),
                ('role', models.CharField(choices=[('USER', 'User'), ('GUARD', 'Guard'), ('ADMIN', 'Admin')], default='USER', max_length=10)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('failed_attempts', models.PositiveSmallIntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=256)),
            ],
            options={
                'db_table': 'auth_otp_token',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone_number', 'is_used'], name='auth_otp_to_phone_n_46e3aa_idx'), models.Index(fields=['expires_at'], name='auth_otp_to_expires_78de31_idx')],
            },
        ),
    ]
