# Generated by Django 6.0.5 on 2026-05-28 09:25

import django_fsm
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_type', models.CharField(choices=[('HOURLY', 'Hourly Protection'), ('DAILY', 'Daily Protection (8h or 12h shift)'), ('WEEKLY', 'Weekly Protection (5 or 7 days)'), ('MONTHLY', 'Monthly Protection (30 days)')], max_length=10)),
                ('guard_type_requested', models.CharField(choices=[('UNARMED', 'Unarmed Guard'), ('ARMED', 'Armed Guard'), ('FEMALE', 'Female Guard'), ('CPO', 'Close Protection Officer'), ('EVENT', 'Event Security')], max_length=10)),
                ('status', django_fsm.FSMField(choices=[('REQUESTED', 'Requested'), ('BROADCAST', 'Broadcasting to Guards'), ('ACCEPTED', 'Guard Accepted'), ('EN_ROUTE', 'Guard En Route'), ('ARRIVED', 'Guard Arrived'), ('ACTIVE', 'Session Active'), ('COMPLETED', 'Session Completed'), ('CANCELLED', 'Cancelled'), ('DISPUTED', 'Disputed'), ('EXPIRED', 'Expired — No Guard Found')], db_index=True, default='REQUESTED', max_length=50)),
                ('scheduled_start', models.DateTimeField()),
                ('scheduled_end', models.DateTimeField()),
                ('is_immediate', models.BooleanField(default=True)),
                ('guard_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('guard_arrived_at', models.DateTimeField(blank=True, null=True)),
                ('session_started_at', models.DateTimeField(blank=True, null=True)),
                ('session_ended_at', models.DateTimeField(blank=True, null=True)),
                ('service_address', models.TextField()),
                ('service_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('service_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('base_rate_per_hour', models.DecimalField(decimal_places=2, max_digits=8)),
                ('surge_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('promo_discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('platform_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('guard_earnings', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('start_otp_hash', models.CharField(blank=True, max_length=64)),
                ('end_otp_hash', models.CharField(blank=True, max_length=64)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence_rule', models.JSONField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('is_flagged', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'bookings_booking',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingBroadcast',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('response', models.CharField(choices=[('SENT', 'Request Sent'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('TIMEOUT', 'No Response — Timed Out')], default='SENT', max_length=10)),
                ('broadcast_radius_km', models.PositiveSmallIntegerField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bookings_broadcast',
            },
        ),
        migrations.CreateModel(
            name='GuardCheckIn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('is_auto', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'bookings_checkin',
                'ordering': ['-created_at'],
            },
        ),
    ]
