# Generated by Django 6.0.5 on 2026-05-28 09:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('guards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.TextField()),
                ('accuracy_meters', models.FloatField(blank=True, null=True)),
                ('speed_kmh', models.FloatField(blank=True, null=True)),
                ('bearing_degrees', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_snapshots', to='bookings.booking')),
                ('guard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_history', to='guards.guardprofile')),
            ],
            options={
                'db_table': 'tracking_location_snapshot',
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['booking', 'timestamp'], name='tracking_lo_booking_e10504_idx'), models.Index(fields=['guard', 'timestamp'], name='tracking_lo_guard_i_642a6b_idx')],
            },
        ),
    ]
