# Generated by Django 6.0.5 on 2026-05-28 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('total_bookings', models.PositiveIntegerField(default=0)),
                ('completed_bookings', models.PositiveIntegerField(default=0)),
                ('cancelled_bookings', models.PositiveIntegerField(default=0)),
                ('disputed_bookings', models.PositiveIntegerField(default=0)),
                ('hourly_bookings', models.PositiveIntegerField(default=0)),
                ('daily_bookings', models.PositiveIntegerField(default=0)),
                ('weekly_bookings', models.PositiveIntegerField(default=0)),
                ('monthly_bookings', models.PositiveIntegerField(default=0)),
                ('gross_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('platform_fees_collected', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('guard_earnings_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('refunds_issued', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('new_users', models.PositiveIntegerField(default=0)),
                ('active_users', models.PositiveIntegerField(default=0)),
                ('new_guards', models.PositiveIntegerField(default=0)),
                ('active_guards', models.PositiveIntegerField(default=0)),
                ('sos_alerts', models.PositiveIntegerField(default=0)),
                ('incidents_filed', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'analytics_daily_stats',
                'ordering': ['-date'],
            },
        ),
    ]
