# Generated by Django 6.0.5 on 2026-05-28 09:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuardAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'guards_availability',
                'ordering': ['weekday', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='GuardBlackoutDate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'guards_blackout_date',
            },
        ),
        migrations.CreateModel(
            name='GuardDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('GOVT_ID', 'Government Photo ID (Aadhaar / Passport / Voter ID)'), ('POLICE_CERT', 'Police Verification Certificate'), ('PSARA_LICENSE', 'PSARA Security Guard License'), ('TRAINING_CERT', 'Security Training Certificate'), ('ARMED_LICENSE', 'Arms License (Armed Guards Only)'), ('PROFILE_PHOTO', 'Live Profile Selfie'), ('ADDRESS_PROOF', 'Address Proof')], max_length=25)),
                ('file', models.FileField(upload_to='guards/documents/')),
                ('file_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded — Awaiting review'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected — Needs resubmission'), ('EXPIRED', 'Expired — Renewal required')], db_index=True, default='UPLOADED', max_length=15)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('expiry_reminder_sent', models.BooleanField(default=False)),
                ('review_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'guards_document',
            },
        ),
        migrations.CreateModel(
            name='GuardProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guard_type', models.CharField(choices=[('UNARMED', 'Unarmed Security Guard'), ('ARMED', 'Armed Security Guard'), ('FEMALE', 'Female Security Guard'), ('CPO', 'Close Protection Officer'), ('EVENT', 'Event Security'), ('K9', 'K9 / Dog Handler')], default='UNARMED', max_length=20)),
                ('years_of_experience', models.PositiveSmallIntegerField(default=0)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('languages_spoken', models.JSONField(default=list)),
                ('skills', models.JSONField(default=list)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending — Documents not yet uploaded'), ('UNDER_REVIEW', 'Under Review — Admin reviewing documents'), ('ACTIVE', 'Active — Verified and can accept bookings'), ('SUSPENDED', 'Suspended — Temporarily deactivated'), ('BANNED', 'Banned — Permanently deactivated'), ('DOCUMENTS_REJECTED', 'Documents Rejected — Needs resubmission')], db_index=True, default='PENDING', max_length=25)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('current_location', models.TextField(blank=True, null=True)),
                ('last_location_update', models.DateTimeField(blank=True, null=True)),
                ('is_online', models.BooleanField(db_index=True, default=False)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('total_sessions_completed', models.PositiveIntegerField(default=0)),
                ('bank_account_number', models.CharField(blank=True, max_length=20)),
                ('bank_ifsc_code', models.CharField(blank=True, max_length=11)),
                ('upi_id', models.CharField(blank=True, max_length=50)),
                ('payout_preference', models.CharField(choices=[('BANK', 'Bank Transfer'), ('UPI', 'UPI')], default='UPI', max_length=10)),
                ('preferred_work_radius_km', models.PositiveSmallIntegerField(default=10)),
                ('max_daily_hours', models.PositiveSmallIntegerField(default=12)),
            ],
            options={
                'db_table': 'guards_profile',
            },
        ),
    ]
