# Generated by Django 6.0.5 on 2026-05-28 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='guarddocument',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='guardprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guard_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='guardprofile',
            name='verified_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guards_verified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='guarddocument',
            name='guard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='guards.guardprofile'),
        ),
        migrations.AddField(
            model_name='guardblackoutdate',
            name='guard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blackout_dates', to='guards.guardprofile'),
        ),
        migrations.AddField(
            model_name='guardavailability',
            name='guard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_schedule', to='guards.guardprofile'),
        ),
        migrations.AddIndex(
            model_name='guardprofile',
            index=models.Index(fields=['verification_status', 'is_online'], name='guards_prof_verific_f87539_idx'),
        ),
        migrations.AddIndex(
            model_name='guardprofile',
            index=models.Index(fields=['guard_type', 'is_online'], name='guards_prof_guard_t_bf6e27_idx'),
        ),
        migrations.AddIndex(
            model_name='guardprofile',
            index=models.Index(fields=['average_rating'], name='guards_prof_average_d2ac58_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='guarddocument',
            unique_together={('guard', 'document_type')},
        ),
        migrations.AlterUniqueTogether(
            name='guardblackoutdate',
            unique_together={('guard', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='guardavailability',
            unique_together={('guard', 'weekday')},
        ),
    ]
