# Generated by Django 6.0.5 on 2026-05-28 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_initial'),
        ('guards', '0002_initial'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payout',
            name='bookings',
            field=models.ManyToManyField(blank=True, related_name='payouts', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='payout',
            name='guard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='guards.guardprofile'),
        ),
        migrations.AddField(
            model_name='payout',
            name='processed_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payouts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='payments.wallet'),
        ),
        migrations.AddIndex(
            model_name='paymentorder',
            index=models.Index(fields=['user', 'status'], name='payments_or_user_id_0f08a8_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentorder',
            index=models.Index(fields=['gateway_order_id'], name='payments_or_gateway_2e8a6a_idx'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['guard', 'status'], name='payments_pa_guard_i_816549_idx'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['status', 'period_start'], name='payments_pa_status_8cef65_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['wallet', 'created_at'], name='payments_tr_wallet__b4df40_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['booking', 'transaction_type'], name='payments_tr_booking_5c8b6b_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['gateway_payment_id'], name='payments_tr_gateway_1ca513_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status', 'transaction_type'], name='payments_tr_status_910420_idx'),
        ),
    ]
